# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_project_track.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1241, 826)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setAutoFillBackground(True)
        Dialog.setSizeGripEnabled(False)
        self.lbl_Title = QtGui.QLabel(Dialog)
        self.lbl_Title.setGeometry(QtCore.QRect(20, 0, 571, 71))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Title.sizePolicy().hasHeightForWidth())
        self.lbl_Title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_Title.setFont(font)
        self.lbl_Title.setObjectName(_fromUtf8("lbl_Title"))
        self.scrollArea = QtGui.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1171, 821))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1152, 819))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.tabMain = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabMain.setGeometry(QtCore.QRect(20, 90, 1111, 651))
        self.tabMain.setAutoFillBackground(False)
        self.tabMain.setUsesScrollButtons(True)
        self.tabMain.setMovable(False)
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.tabPrjSetUp = QtGui.QWidget()
        self.tabPrjSetUp.setObjectName(_fromUtf8("tabPrjSetUp"))
        self.txtProject = QtGui.QTextEdit(self.tabPrjSetUp)
        self.txtProject.setGeometry(QtCore.QRect(130, 40, 161, 31))
        self.txtProject.setTabChangesFocus(True)
        self.txtProject.setObjectName(_fromUtf8("txtProject"))
        self.label = QtGui.QLabel(self.tabPrjSetUp)
        self.label.setGeometry(QtCore.QRect(10, 50, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_3.setGeometry(QtCore.QRect(10, 153, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.rbFundsTrnsfrd = QtGui.QRadioButton(self.tabPrjSetUp)
        self.rbFundsTrnsfrd.setGeometry(QtCore.QRect(410, 158, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbFundsTrnsfrd.setFont(font)
        self.rbFundsTrnsfrd.setObjectName(_fromUtf8("rbFundsTrnsfrd"))
        self.label_4 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_4.setGeometry(QtCore.QRect(10, 393, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.sbxHrlyrate = QtGui.QDoubleSpinBox(self.tabPrjSetUp)
        self.sbxHrlyrate.setGeometry(QtCore.QRect(190, 393, 101, 27))
        self.sbxHrlyrate.setMaximum(200.0)
        self.sbxHrlyrate.setProperty("value", 78.0)
        self.sbxHrlyrate.setObjectName(_fromUtf8("sbxHrlyrate"))
        self.sbxBudgetGross = QtGui.QDoubleSpinBox(self.tabPrjSetUp)
        self.sbxBudgetGross.setGeometry(QtCore.QRect(190, 150, 101, 27))
        self.sbxBudgetGross.setToolTip(_fromUtf8(""))
        self.sbxBudgetGross.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.sbxBudgetGross.setMaximum(500000.0)
        self.sbxBudgetGross.setSingleStep(1000.0)
        self.sbxBudgetGross.setObjectName(_fromUtf8("sbxBudgetGross"))
        self.label_5 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_5.setGeometry(QtCore.QRect(10, 224, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.sbxFixedPM = QtGui.QDoubleSpinBox(self.tabPrjSetUp)
        self.sbxFixedPM.setGeometry(QtCore.QRect(190, 223, 101, 27))
        self.sbxFixedPM.setMaximum(200.0)
        self.sbxFixedPM.setObjectName(_fromUtf8("sbxFixedPM"))
        self.label_6 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_6.setGeometry(QtCore.QRect(10, 190, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.sbxOH = QtGui.QDoubleSpinBox(self.tabPrjSetUp)
        self.sbxOH.setGeometry(QtCore.QRect(190, 190, 101, 27))
        self.sbxOH.setMaximum(100.0)
        self.sbxOH.setProperty("value", 15.0)
        self.sbxOH.setObjectName(_fromUtf8("sbxOH"))
        self.txtDevFunding = QtGui.QTextEdit(self.tabPrjSetUp)
        self.txtDevFunding.setGeometry(QtCore.QRect(150, 510, 161, 31))
        self.txtDevFunding.setToolTip(_fromUtf8(""))
        self.txtDevFunding.setTabChangesFocus(True)
        self.txtDevFunding.setObjectName(_fromUtf8("txtDevFunding"))
        self.label_7 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_7.setGeometry(QtCore.QRect(10, 520, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.txtDevHrs = QtGui.QTextEdit(self.tabPrjSetUp)
        self.txtDevHrs.setGeometry(QtCore.QRect(150, 550, 161, 31))
        self.txtDevHrs.setTabChangesFocus(True)
        self.txtDevHrs.setObjectName(_fromUtf8("txtDevHrs"))
        self.label_8 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_8.setGeometry(QtCore.QRect(10, 560, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.pbCalcDev = QtGui.QPushButton(self.tabPrjSetUp)
        self.pbCalcDev.setGeometry(QtCore.QRect(390, 430, 99, 27))
        self.pbCalcDev.setObjectName(_fromUtf8("pbCalcDev"))
        self.pbPostNewProj = QtGui.QPushButton(self.tabPrjSetUp)
        self.pbPostNewProj.setGeometry(QtCore.QRect(390, 590, 99, 27))
        self.pbPostNewProj.setObjectName(_fromUtf8("pbPostNewProj"))
        self.label_9 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.cbxPI = QtGui.QComboBox(self.tabPrjSetUp)
        self.cbxPI.setGeometry(QtCore.QRect(40, 80, 221, 22))
        self.cbxPI.setObjectName(_fromUtf8("cbxPI"))
        self.sbxYear = QtGui.QSpinBox(self.tabPrjSetUp)
        self.sbxYear.setGeometry(QtCore.QRect(160, 10, 51, 21))
        self.sbxYear.setMinimum(2015)
        self.sbxYear.setMaximum(2025)
        self.sbxYear.setProperty("value", 2017)
        self.sbxYear.setObjectName(_fromUtf8("sbxYear"))
        self.label_10 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_10.setGeometry(QtCore.QRect(10, 15, 68, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.txtAssumptions = QtGui.QTextEdit(self.tabPrjSetUp)
        self.txtAssumptions.setGeometry(QtCore.QRect(570, 479, 501, 101))
        self.txtAssumptions.setTabChangesFocus(True)
        self.txtAssumptions.setObjectName(_fromUtf8("txtAssumptions"))
        self.label_11 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_11.setGeometry(QtCore.QRect(570, 459, 241, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.cbxPM = QtGui.QComboBox(self.tabPrjSetUp)
        self.cbxPM.setGeometry(QtCore.QRect(390, 80, 221, 22))
        self.cbxPM.setObjectName(_fromUtf8("cbxPM"))
        self.label_12 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_12.setGeometry(QtCore.QRect(360, 85, 31, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.cbxSponsor = QtGui.QComboBox(self.tabPrjSetUp)
        self.cbxSponsor.setGeometry(QtCore.QRect(168, 120, 261, 22))
        self.cbxSponsor.setObjectName(_fromUtf8("cbxSponsor"))
        self.label_13 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_13.setGeometry(QtCore.QRect(10, 480, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.txtNetFunds = QtGui.QTextEdit(self.tabPrjSetUp)
        self.txtNetFunds.setGeometry(QtCore.QRect(150, 470, 161, 31))
        self.txtNetFunds.setToolTip(_fromUtf8(""))
        self.txtNetFunds.setTabChangesFocus(True)
        self.txtNetFunds.setObjectName(_fromUtf8("txtNetFunds"))
        self.label_14 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_14.setGeometry(QtCore.QRect(320, 50, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.txtPrjCode = QtGui.QTextEdit(self.tabPrjSetUp)
        self.txtPrjCode.setGeometry(QtCore.QRect(450, 40, 161, 31))
        self.txtPrjCode.setTabChangesFocus(True)
        self.txtPrjCode.setObjectName(_fromUtf8("txtPrjCode"))
        self.gbPM = QtGui.QGroupBox(self.tabPrjSetUp)
        self.gbPM.setGeometry(QtCore.QRect(300, 217, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.gbPM.setFont(font)
        self.gbPM.setAutoFillBackground(True)
        self.gbPM.setTitle(_fromUtf8(""))
        self.gbPM.setFlat(False)
        self.gbPM.setObjectName(_fromUtf8("gbPM"))
        self.rbPMpct = QtGui.QRadioButton(self.gbPM)
        self.rbPMpct.setGeometry(QtCore.QRect(10, 0, 51, 17))
        self.rbPMpct.setChecked(True)
        self.rbPMpct.setObjectName(_fromUtf8("rbPMpct"))
        self.rbPMcur = QtGui.QRadioButton(self.gbPM)
        self.rbPMcur.setGeometry(QtCore.QRect(10, 20, 51, 17))
        self.rbPMcur.setObjectName(_fromUtf8("rbPMcur"))
        self.label_15 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_15.setGeometry(QtCore.QRect(10, 274, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.sbxFixedSys = QtGui.QDoubleSpinBox(self.tabPrjSetUp)
        self.sbxFixedSys.setGeometry(QtCore.QRect(192, 270, 101, 27))
        self.sbxFixedSys.setMaximum(200.0)
        self.sbxFixedSys.setObjectName(_fromUtf8("sbxFixedSys"))
        self.gbSys = QtGui.QGroupBox(self.tabPrjSetUp)
        self.gbSys.setGeometry(QtCore.QRect(300, 266, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.gbSys.setFont(font)
        self.gbSys.setAutoFillBackground(True)
        self.gbSys.setTitle(_fromUtf8(""))
        self.gbSys.setFlat(False)
        self.gbSys.setObjectName(_fromUtf8("gbSys"))
        self.rbSYSpct = QtGui.QRadioButton(self.gbSys)
        self.rbSYSpct.setGeometry(QtCore.QRect(10, 0, 51, 17))
        self.rbSYSpct.setChecked(True)
        self.rbSYSpct.setObjectName(_fromUtf8("rbSYSpct"))
        self.rbSYScur = QtGui.QRadioButton(self.gbSys)
        self.rbSYScur.setGeometry(QtCore.QRect(10, 20, 51, 17))
        self.rbSYScur.setObjectName(_fromUtf8("rbSYScur"))
        self.sbxFed = QtGui.QDoubleSpinBox(self.tabPrjSetUp)
        self.sbxFed.setGeometry(QtCore.QRect(190, 357, 101, 27))
        self.sbxFed.setMaximum(200.0)
        self.sbxFed.setObjectName(_fromUtf8("sbxFed"))
        self.label_16 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_16.setGeometry(QtCore.QRect(10, 365, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gbFed = QtGui.QGroupBox(self.tabPrjSetUp)
        self.gbFed.setGeometry(QtCore.QRect(300, 350, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.gbFed.setFont(font)
        self.gbFed.setAutoFillBackground(True)
        self.gbFed.setTitle(_fromUtf8(""))
        self.gbFed.setFlat(False)
        self.gbFed.setObjectName(_fromUtf8("gbFed"))
        self.rbFEDpct = QtGui.QRadioButton(self.gbFed)
        self.rbFEDpct.setGeometry(QtCore.QRect(10, 0, 51, 17))
        self.rbFEDpct.setChecked(True)
        self.rbFEDpct.setObjectName(_fromUtf8("rbFEDpct"))
        self.rbFEDcur = QtGui.QRadioButton(self.gbFed)
        self.rbFEDcur.setGeometry(QtCore.QRect(10, 20, 51, 17))
        self.rbFEDcur.setObjectName(_fromUtf8("rbFEDcur"))
        self.rbFEDcur.raise_()
        self.rbFEDpct.raise_()
        self.sbxHosting = QtGui.QDoubleSpinBox(self.tabPrjSetUp)
        self.sbxHosting.setGeometry(QtCore.QRect(190, 317, 101, 27))
        self.sbxHosting.setMaximum(1000.0)
        self.sbxHosting.setObjectName(_fromUtf8("sbxHosting"))
        self.label_17 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_17.setGeometry(QtCore.QRect(10, 320, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.txtTO = QtGui.QLineEdit(self.tabPrjSetUp)
        self.txtTO.setEnabled(False)
        self.txtTO.setGeometry(QtCore.QRect(670, 160, 141, 20))
        self.txtTO.setObjectName(_fromUtf8("txtTO"))
        self.lblTO = QtGui.QLabel(self.tabPrjSetUp)
        self.lblTO.setEnabled(False)
        self.lblTO.setGeometry(QtCore.QRect(570, 160, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblTO.setFont(font)
        self.lblTO.setObjectName(_fromUtf8("lblTO"))
        self.sbxFiscalYear = QtGui.QSpinBox(self.tabPrjSetUp)
        self.sbxFiscalYear.setGeometry(QtCore.QRect(580, 125, 51, 21))
        self.sbxFiscalYear.setMinimum(2015)
        self.sbxFiscalYear.setMaximum(2025)
        self.sbxFiscalYear.setProperty("value", 2017)
        self.sbxFiscalYear.setObjectName(_fromUtf8("sbxFiscalYear"))
        self.label_18 = QtGui.QLabel(self.tabPrjSetUp)
        self.label_18.setGeometry(QtCore.QRect(500, 125, 68, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.tabMain.addTab(self.tabPrjSetUp, _fromUtf8(""))
        self.tabPrjReview = QtGui.QWidget()
        self.tabPrjReview.setObjectName(_fromUtf8("tabPrjReview"))
        self.tblReviewProj = QtGui.QTableWidget(self.tabPrjReview)
        self.tblReviewProj.setGeometry(QtCore.QRect(5, 60, 1101, 561))
        self.tblReviewProj.setRowCount(55)
        self.tblReviewProj.setColumnCount(21)
        self.tblReviewProj.setObjectName(_fromUtf8("tblReviewProj"))
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tblReviewProj.setHorizontalHeaderItem(20, item)
        self.tblReviewProj.horizontalHeader().setCascadingSectionResizes(True)
        self.tblReviewProj.horizontalHeader().setSortIndicatorShown(True)
        self.tblReviewProj.verticalHeader().setVisible(False)
        self.tabMain.addTab(self.tabPrjReview, _fromUtf8(""))
        self.lbl_ver = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lbl_ver.setGeometry(QtCore.QRect(940, 80, 171, 16))
        self.lbl_ver.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_ver.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_ver.setObjectName(_fromUtf8("lbl_ver"))
        self.pbClose = QtGui.QDialogButtonBox(self.scrollAreaWidgetContents)
        self.pbClose.setGeometry(QtCore.QRect(1020, 770, 91, 32))
        self.pbClose.setOrientation(QtCore.Qt.Horizontal)
        self.pbClose.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.pbClose.setObjectName(_fromUtf8("pbClose"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea.raise_()
        self.lbl_Title.raise_()

        self.retranslateUi(Dialog)
        self.tabMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.sbxYear, self.txtProject)
        Dialog.setTabOrder(self.txtProject, self.txtPrjCode)
        Dialog.setTabOrder(self.txtPrjCode, self.cbxPI)
        Dialog.setTabOrder(self.cbxPI, self.cbxPM)
        Dialog.setTabOrder(self.cbxPM, self.cbxSponsor)
        Dialog.setTabOrder(self.cbxSponsor, self.sbxFiscalYear)
        Dialog.setTabOrder(self.sbxFiscalYear, self.sbxBudgetGross)
        Dialog.setTabOrder(self.sbxBudgetGross, self.rbFundsTrnsfrd)
        Dialog.setTabOrder(self.rbFundsTrnsfrd, self.txtTO)
        Dialog.setTabOrder(self.txtTO, self.sbxOH)
        Dialog.setTabOrder(self.sbxOH, self.sbxFixedPM)
        Dialog.setTabOrder(self.sbxFixedPM, self.rbPMpct)
        Dialog.setTabOrder(self.rbPMpct, self.rbPMcur)
        Dialog.setTabOrder(self.rbPMcur, self.sbxFixedSys)
        Dialog.setTabOrder(self.sbxFixedSys, self.rbSYSpct)
        Dialog.setTabOrder(self.rbSYSpct, self.rbSYScur)
        Dialog.setTabOrder(self.rbSYScur, self.sbxHosting)
        Dialog.setTabOrder(self.sbxHosting, self.sbxFed)
        Dialog.setTabOrder(self.sbxFed, self.rbFEDpct)
        Dialog.setTabOrder(self.rbFEDpct, self.rbFEDcur)
        Dialog.setTabOrder(self.rbFEDcur, self.sbxHrlyrate)
        Dialog.setTabOrder(self.sbxHrlyrate, self.pbCalcDev)
        Dialog.setTabOrder(self.pbCalcDev, self.txtNetFunds)
        Dialog.setTabOrder(self.txtNetFunds, self.txtDevFunding)
        Dialog.setTabOrder(self.txtDevFunding, self.txtDevHrs)
        Dialog.setTabOrder(self.txtDevHrs, self.txtAssumptions)
        Dialog.setTabOrder(self.txtAssumptions, self.pbPostNewProj)
        Dialog.setTabOrder(self.pbPostNewProj, self.pbClose)
        Dialog.setTabOrder(self.pbClose, self.tblReviewProj)
        Dialog.setTabOrder(self.tblReviewProj, self.scrollArea)
        Dialog.setTabOrder(self.scrollArea, self.tabMain)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.lbl_Title.setText(_translate("Dialog", "Web Applications Tracking Tool", None))
        self.label.setText(_translate("Dialog", "Project Name:", None))
        self.label_2.setText(_translate("Dialog", "Sponsoring Agency or Program", None))
        self.label_3.setText(_translate("Dialog", "Budget (Gross)", None))
        self.rbFundsTrnsfrd.setText(_translate("Dialog", "Funds Tranfered?", None))
        self.label_4.setText(_translate("Dialog", "Assumed Hourly Rate", None))
        self.label_5.setText(_translate("Dialog", "Fixed - PM/QA", None))
        self.label_6.setText(_translate("Dialog", "Overhead (%)", None))
        self.label_7.setText(_translate("Dialog", "Development Funds", None))
        self.label_8.setText(_translate("Dialog", "Development Hours", None))
        self.pbCalcDev.setText(_translate("Dialog", "Calculate", None))
        self.pbPostNewProj.setText(_translate("Dialog", "Post", None))
        self.label_9.setText(_translate("Dialog", "PI:", None))
        self.label_10.setText(_translate("Dialog", "Start Year", None))
        self.label_11.setText(_translate("Dialog", "Notes and Assumptions (put date)", None))
        self.label_12.setText(_translate("Dialog", "PM:", None))
        self.label_13.setText(_translate("Dialog", "Net Funds", None))
        self.label_14.setText(_translate("Dialog", "Project Acronym:", None))
        self.rbPMpct.setText(_translate("Dialog", "%", None))
        self.rbPMcur.setText(_translate("Dialog", "$", None))
        self.label_15.setText(_translate("Dialog", "Fixed - Systems", None))
        self.rbSYSpct.setText(_translate("Dialog", "%", None))
        self.rbSYScur.setText(_translate("Dialog", "$", None))
        self.label_16.setText(_translate("Dialog", "Federal", None))
        self.rbFEDpct.setText(_translate("Dialog", "%", None))
        self.rbFEDcur.setText(_translate("Dialog", "$", None))
        self.label_17.setText(_translate("Dialog", "Hosting Costs", None))
        self.lblTO.setText(_translate("Dialog", "Task Order:", None))
        self.label_18.setText(_translate("Dialog", "Fiscal Year", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabPrjSetUp), _translate("Dialog", "New Project Set Up", None))
        item = self.tblReviewProj.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Agency", None))
        item = self.tblReviewProj.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Project", None))
        item = self.tblReviewProj.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Task Order", None))
        item = self.tblReviewProj.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "PI", None))
        item = self.tblReviewProj.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Funded", None))
        item = self.tblReviewProj.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Hours", None))
        item = self.tblReviewProj.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "January", None))
        item = self.tblReviewProj.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "February", None))
        item = self.tblReviewProj.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "March", None))
        item = self.tblReviewProj.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "April", None))
        item = self.tblReviewProj.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "May", None))
        item = self.tblReviewProj.horizontalHeaderItem(11)
        item.setText(_translate("Dialog", "June", None))
        item = self.tblReviewProj.horizontalHeaderItem(12)
        item.setText(_translate("Dialog", "July", None))
        item = self.tblReviewProj.horizontalHeaderItem(13)
        item.setText(_translate("Dialog", "August", None))
        item = self.tblReviewProj.horizontalHeaderItem(14)
        item.setText(_translate("Dialog", "September", None))
        item = self.tblReviewProj.horizontalHeaderItem(15)
        item.setText(_translate("Dialog", "October", None))
        item = self.tblReviewProj.horizontalHeaderItem(16)
        item.setText(_translate("Dialog", "November", None))
        item = self.tblReviewProj.horizontalHeaderItem(17)
        item.setText(_translate("Dialog", "December", None))
        item = self.tblReviewProj.horizontalHeaderItem(18)
        item.setText(_translate("Dialog", "Total Hours Spent", None))
        item = self.tblReviewProj.horizontalHeaderItem(19)
        item.setText(_translate("Dialog", "Total Hours", None))
        item = self.tblReviewProj.horizontalHeaderItem(20)
        item.setText(_translate("Dialog", "Total Fund Remaining", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabPrjReview), _translate("Dialog", "Project Review", None))
        self.lbl_ver.setText(_translate("Dialog", "V0.01 2016-11-25", None))

